/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Rubber Duck.glb -o ./src/duck.tsx --transform --types 
Files: ./public/Rubber Duck.glb [1.12MB] > /Users/christopherneale/projects/shooter/ddbh/src/Rubber Duck-transformed.glb [18.61KB] (98%)
*/

import { useMemo, type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { Color, type Mesh, type MeshStandardMaterial } from 'three'

type GLTFResult = GLTF & {
  nodes: {
    RubberDuck_mesh: Mesh
  }
  materials: {
    RubberDuck_mat1: MeshStandardMaterial
  }
}

export const useDuckModel = () =>
  useGLTF('/RubberDuck-transformed.glb') as unknown as GLTFResult

export function Duck(props: JSX.IntrinsicElements['group'] & { tintColor?: string }) {
  const { nodes, materials } = useDuckModel()
  const { tintColor, ...rest } = props

  // Derive a material: default GLTF material, or a cloned tinted variant
  const material = useMemo(() => {
    if (!tintColor) return materials.RubberDuck_mat1
    const m = materials.RubberDuck_mat1.clone()
    m.color = new Color(tintColor)
    return m
  }, [materials.RubberDuck_mat1, tintColor])

  return (
    <group {...rest} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.RubberDuck_mesh.geometry} material={material} />
    </group>
  )
}

useGLTF.preload('/RubberDuck-transformed.glb')
